services:
  - type: web
    name: flask-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2